name: Release Go Binaries

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  releases-matrix:
    name: Release Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          check-latest: true

      - name: Build Binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          binary_name="api-${{ matrix.goos }}-${{ matrix.goarch }}"
          if [ "${{ matrix.goos }}" = "windows" ]; then
            binary_name="$binary_name.exe"
          fi
          go build -v -o "dist/$binary_name" ./cmd/myapp

      - name: Generate SHA256 Checksum
        if: matrix.goos != 'windows'
        run: |
          cd dist
          sha256sum * > checksums.txt

      - name: Generate SHA256 Checksum (Windows)
        if: matrix.goos == 'windows'
        run: |
          cd dist
          CertUtil -hashfile * SHA256 > checksums.txt

      - name: Upload Binary to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
